const DummyCommunity = [
   {
      id: 1,
      title: '안녕하세요1',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'rayoon yang',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 2,
      title: '안녕하세요2',
      comment: 3,
      date: '07/08',
      detailDate: '025/07/08 08:30',
      view: 123,
      writer: 'rayoon yang',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 3,
      title: '안녕하세요3',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'rayoon yang',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 4,
      title: '안녕하세요4',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'rayoon yang',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 5,
      title: '안녕하세요5',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'rayoon yang',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 6,
      title: '안녕하세요6',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'rayoon yang',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 7,
      title: '안녕하세요7',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'rayoon yang',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 8,
      title: '안녕하세요8',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'rayoon yang',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 9,
      title: '안녕하세요9',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'rayoon yang',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 10,
      title: '안녕하세요10',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'rayoon yang',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 11,
      title: '안녕하세요1',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'yeen park',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 12,
      title: '안녕하세요2',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'yeen park',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 13,
      title: '안녕하세요3',
      comment: 3,
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'yeen park',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 14,
      title: '안녕하세요4',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'yeen park',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 15,
      title: '안녕하세요5',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'yeen park',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 16,
      title: '안녕하세요6',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'yeen park',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 17,
      title: '안녕하세요7',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'yeen park',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 18,
      title: '안녕하세요8',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'yeen park',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 19,
      title: '안녕하세요9',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'yeen park',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
   {
      id: 20,
      title: '안녕하세요10',
      comment: 3,
      date: '07/08',
      detailDate: '25/07/08 08:30',
      view: 123,
      writer: 'yeen park',
      article: '안녕하세용가리 등업 부탁 플리즈 ~ ! https://www.google.com',
      like: 120,
   },
];

export default DummyCommunity;
